### PR TITLE
Multiple additions

### PR DESCRIPTION
**Pull request by jvandenbroek**
Changed quite a few things, maybe you can review them for inclusion? Tested it with all different possible settings and works well here. Thank you!

### CODE REVIEW

**Comment by owagner** [comment]
Cool!

Could you bring the PR up-to-date with HEAD?

Also, is the distinction of title- and pathname filtering really necessary? Perhaps the keywords could simply be matched against both.

Does this mechanism allow filtering of the content delivered by specific add-ons?

**Comment by jvandenbroek** [comment]
Absolutely, in sync now. I reverted the distinction, I was doubting about that as well.

Not sure what you mean, other add-ons are also using the build-in Kodi functions for playing content? At least it works well with the Youtube add-on.

**Comment by owagner** [comment]
Regarding retries, it's perhaps not necessary to make this an option, and just retry endlessly, perhaps with exponential backoff? A failed tcp connect() really isn't that big a resource waste...

**Comment by jvandenbroek** [comment]
Not sure how much overhead that generates, but I can think of people who accidentally keeps this add-on enabled when the MQTT server no longer is available (could happen to me ;-) in which case, it would be better not to keep trying to connect all the time. But probably it would be better than just stop the service instead, so I see your point that with the current implementation there is little to no overhead. I think it would make sense to make it non-configurable and probably just give up after a few minutes of trying.

**Pull request merged**
